/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import presentador.PresentadorGeneral;

/**
 *
 * @author PC1
 */
public class PanelInforme2 extends javax.swing.JPanel {

    private PresentadorGeneral pGeneral;
    private DefaultTableModel model;

    /**
     * Creates new form PanelInforme2
     */
    public PanelInforme2(PresentadorGeneral pGeneral) {
        initComponents();
        this.pGeneral = pGeneral;
        model = (DefaultTableModel) jTable1.getModel();
    }

    public JTable getTablaInformes1() {
        return jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtFld_nombreArchivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(766, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nombre: Alumnos de pregrado en el servicio de medicina, por sexo segun escuelas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Archivo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        TxtFld_nombreArchivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxtFld_nombreArchivo.setPreferredSize(new java.awt.Dimension(200, 30));
        TxtFld_nombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFld_nombreArchivoActionPerformed(evt);
            }
        });
        add(TxtFld_nombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 57, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText(".pdf");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 60, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(706, 365));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Departamento", "Escuela", "Masculino", "Femenino", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFld_nombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFld_nombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFld_nombreArchivoActionPerformed
    public void cargarInformesEnTabla(List<Object[]> informes) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Object[] informe : informes) {
            model.addRow(informe);
        }
    }

    String[] obtenerEncabezados() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int columnCount = model.getColumnCount();
        String[] headers = new String[columnCount];

        for (int i = 0; i < columnCount; i++) {
            headers[i] = model.getColumnName(i);
        }
        return headers;
    }

    public String obtenerNombreArchivo() {
        return TxtFld_nombreArchivo.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtFld_nombreArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
